//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBook()
        {
            this.TblProcess = new HashSet<TblProcess>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Writer { get; set; }
        public string ReleaseYear { get; set; }
        public string Publisher { get; set; }
        public string Page { get; set; }
        public Nullable<bool> Situation { get; set; }
        public string Photo { get; set; }
    
        public virtual TblCategory TblCategory { get; set; }
        public virtual TblWriter TblWriter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProcess> TblProcess { get; set; }
    }
}
