//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBan
    {
        public int ID { get; set; }
        public Nullable<int> Member { get; set; }
        public Nullable<int> Process { get; set; }
        public Nullable<System.DateTime> BanDate { get; set; }
        public Nullable<System.DateTime> BanEndTime { get; set; }
        public Nullable<decimal> Fine { get; set; }
    
        public virtual TblMembers TblMembers { get; set; }
        public virtual TblProcess TblProcess { get; set; }
    }
}
